// <auto-generated />
using System;
using HotelGenericoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelGenericoApi.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260518222621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelGenericoApi.Models.AfectacionIgv", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("char(2)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("Codigo");

                    b.ToTable("afectacion_igv", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.ToTable("categoria_producto", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.CierreCajaEnvio", b =>
                {
                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_envio");

                    b.Property<string>("HashXml")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("hash_xml");

                    b.Property<int>("IdEstadoSunat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id_estado_sunat");

                    b.Property<int?>("IntentosEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_envio");

                    b.HasKey("Fecha");

                    b.HasIndex("IdEstadoSunat");

                    b.ToTable("cierre_caja_envio", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaVerificacionReniec")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_verificacion_reniec");

                    b.Property<string>("Nacionalidad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PERUANA")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("IdCliente");

                    b.HasIndex("TipoDocumento", "Documento")
                        .IsUnique()
                        .HasDatabaseName("uq_cliente_documento");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Comprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComprobante"));

                    b.Property<byte[]>("CdrZip")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("cdr_zip");

                    b.Property<string>("ClienteDocumentoNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cliente_documento_num");

                    b.Property<string>("ClienteDocumentoTipo")
                        .HasColumnType("char(1)")
                        .HasColumnName("cliente_documento_tipo");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cliente_nombre");

                    b.Property<int>("Correlativo")
                        .HasColumnType("int")
                        .HasColumnName("correlativo");

                    b.Property<DateTime?>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_emision")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_envio");

                    b.Property<string>("HashXml")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("hash_xml");

                    b.Property<int>("IdEstadoSunat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id_estado_sunat");

                    b.Property<int?>("IdEstancia")
                        .HasColumnType("int")
                        .HasColumnName("id_estancia");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("IgvMonto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("igv_monto");

                    b.Property<int?>("IntentosEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_envio");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("char(3)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("serie");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("tipo_comprobante");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("xml_firmado");

                    b.HasKey("IdComprobante");

                    b.HasIndex("FechaEmision")
                        .HasDatabaseName("ix_comprobante_fecha_emision");

                    b.HasIndex("IdEstadoSunat");

                    b.HasIndex("IdEstancia");

                    b.HasIndex("IdVenta");

                    b.HasIndex("MetodoPago");

                    b.HasIndex("TipoComprobante");

                    b.HasIndex("ClienteDocumentoTipo", "ClienteDocumentoNum")
                        .HasDatabaseName("ix_comprobante_cliente");

                    b.HasIndex("Serie", "Correlativo")
                        .IsUnique()
                        .HasDatabaseName("uq_comprobante_serie_correlativo");

                    b.ToTable("comprobante", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Configuracion", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id_configuracion");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ruc")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("ruc");

                    b.Property<decimal>("TasaIgvHotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(18.00m)
                        .HasColumnName("tasa_igv_hotel");

                    b.Property<decimal>("TasaIgvProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(18.00m)
                        .HasColumnName("tasa_igv_productos");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdConfiguracion");

                    b.ToTable("configuracion", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.EstadoHabitacion", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("ColorUi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("color_ui");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsEstadoFinal")
                        .HasColumnType("bit")
                        .HasColumnName("es_estado_final");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.Property<bool>("PermiteCheckin")
                        .HasColumnType("bit")
                        .HasColumnName("permite_checkin");

                    b.Property<bool>("PermiteCheckout")
                        .HasColumnType("bit")
                        .HasColumnName("permite_checkout");

                    b.HasKey("IdEstado");

                    b.ToTable("estado_habitacion", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.EstadoSunat", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DescripcionLarga")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion_larga");

                    b.HasKey("Codigo");

                    b.ToTable("estado_sunat", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Estancia", b =>
                {
                    b.Property<int>("IdEstancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estancia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstancia"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activa")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCheckin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_checkin");

                    b.Property<DateTime>("FechaCheckoutPrevista")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_checkout_prevista");

                    b.Property<DateTime?>("FechaCheckoutReal")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_checkout_real");

                    b.Property<int>("IdClienteTitular")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente_titular");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("id_habitacion");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("IdEstancia");

                    b.HasIndex("IdClienteTitular");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdReserva");

                    b.ToTable("estancia", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Habitacion", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_habitacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaUltimoCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ultimo_cambio")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<string>("NumeroHabitacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("numero_habitacion");

                    b.Property<int?>("Piso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("piso");

                    b.Property<decimal>("PrecioNoche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(50.00m)
                        .HasColumnName("precio_noche");

                    b.Property<int?>("UsuarioCambio")
                        .HasColumnType("int")
                        .HasColumnName("usuario_cambio");

                    b.HasKey("IdHabitacion");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipo");

                    b.HasIndex("NumeroHabitacion")
                        .IsUnique()
                        .HasDatabaseName("uq_habitacion_numero");

                    b.HasIndex("UsuarioCambio");

                    b.ToTable("habitacion", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.HistorialEstadoHabitacion", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime?>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdEstadoAnterior")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_anterior");

                    b.Property<int?>("IdEstadoNuevo")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_nuevo");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("id_habitacion");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("observacion");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdHabitacion", "FechaCambio")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_historial_habitacion_fecha");

                    b.ToTable("historial_estado_habitacion", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Huesped", b =>
                {
                    b.Property<int>("IdHuesped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_huesped");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHuesped"));

                    b.Property<bool?>("EsTitular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("es_titular");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstancia")
                        .HasColumnType("int")
                        .HasColumnName("id_estancia");

                    b.HasKey("IdHuesped");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstancia");

                    b.ToTable("huesped", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.ItemEstancia", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdEstancia")
                        .HasColumnType("int")
                        .HasColumnName("id_estancia");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal")
                        .HasComputedColumnSql("(cantidad * precio_unitario)", true);

                    b.HasKey("IdItem");

                    b.HasIndex("IdEstancia")
                        .HasDatabaseName("ix_item_estancia_estancia");

                    b.HasIndex("IdProducto");

                    b.ToTable("item_estancia", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.ItemVenta", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal")
                        .HasComputedColumnSql("(cantidad * precio_unitario)", true);

                    b.HasKey("IdItem");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta")
                        .HasDatabaseName("ix_item_venta_venta");

                    b.ToTable("item_venta", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.LoginAttempt", b =>
                {
                    b.Property<int>("IdLoginAttempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_login_attempt");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoginAttempt"));

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("attempted_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit")
                        .HasColumnName("succeeded");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("IdLoginAttempt");

                    b.HasIndex("IpAddress", "AttemptedAt")
                        .HasDatabaseName("ix_login_attempt_ip_fecha");

                    b.HasIndex("Username", "AttemptedAt")
                        .HasDatabaseName("IX_login_attempt_username_at");

                    b.ToTable("login_attempt", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.MetodoPago", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("Codigo");

                    b.ToTable("metodo_pago", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("CodigoSunat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo_sunat");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("IdAfectacionIgv")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("10")
                        .HasColumnName("id_afectacion_igv");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.Property<int?>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("NIU")
                        .HasColumnName("unidad_medida");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoSunat")
                        .HasDatabaseName("ix_producto_codigo_sunat");

                    b.HasIndex("IdAfectacionIgv");

                    b.HasIndex("IdCategoria");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<bool>("EsNoShow")
                        .HasColumnType("bit")
                        .HasColumnName("es_no_show");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntradaPrevista")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_entrada_prevista");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaSalidaPrevista")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_salida_prevista");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("id_habitacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.RolUsuario", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.ToTable("rol_usuario", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Tarifa", b =>
                {
                    b.Property<int>("IdTarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tarifa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarifa"));

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdTemporada")
                        .HasColumnType("int")
                        .HasColumnName("id_temporada");

                    b.Property<int>("IdTipoHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_habitacion");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdTarifa");

                    b.HasIndex("IdTemporada");

                    b.HasIndex("IdTipoHabitacion");

                    b.ToTable("tarifa", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Temporada", b =>
                {
                    b.Property<int>("IdTemporada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_temporada");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTemporada"));

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal>("Multiplicador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(1.00m)
                        .HasColumnName("multiplicador");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTemporada");

                    b.ToTable("temporada", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.TipoComprobante", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("char(2)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("Codigo");

                    b.ToTable("tipo_comprobante", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.TipoDocumento", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("char(1)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("Codigo");

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.TipoHabitacion", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<int?>("Capacidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("capacidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(50.00m)
                        .HasColumnName("precio_base");

                    b.HasKey("IdTipo");

                    b.ToTable("tipo_habitacion", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.TransicionEstado", b =>
                {
                    b.Property<int>("IdTransicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_transicion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransicion"));

                    b.Property<int>("IdEstadoActual")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_actual");

                    b.Property<int>("IdEstadoSiguiente")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_siguiente");

                    b.HasKey("IdTransicion");

                    b.HasIndex("IdEstadoSiguiente");

                    b.HasIndex("IdEstadoActual", "IdEstadoSiguiente")
                        .IsUnique()
                        .HasDatabaseName("uq_transicion");

                    b.ToTable("transicion_estado", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("DebeCambiarPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("debe_cambiar_password");

                    b.Property<bool?>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("esta_activo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.VCierreCajaDiario", b =>
                {
                    b.Property<string>("Concepto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concepto");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Ingresos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ingresos");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metodo_pago");

                    b.ToTable((string)null);

                    b.ToView("v_cierre_caja_diario", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.VEstadoHabitacion", b =>
                {
                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaUltimoCambio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ultimo_cambio");

                    b.Property<string>("NumeroHabitacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero_habitacion");

                    b.Property<decimal>("PrecioNoche")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_noche");

                    b.Property<string>("TipoHabitacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_habitacion");

                    b.ToTable((string)null);

                    b.ToView("v_estado_habitaciones", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.VOcupacionDiaria", b =>
                {
                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("Ocupadas")
                        .HasColumnType("int")
                        .HasColumnName("ocupadas");

                    b.Property<decimal>("PorcentajeOcupacion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("porcentaje_ocupacion");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.ToTable((string)null);

                    b.ToView("v_ocupacion_diaria", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("MetodoPago");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("HotelGenericoApi.Models.CierreCajaEnvio", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.EstadoSunat", "EstadoSunat")
                        .WithMany()
                        .HasForeignKey("IdEstadoSunat")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_cierre_estado_sunat");

                    b.Navigation("EstadoSunat");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Cliente", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.TipoDocumento", "TipoDocumentoNavigation")
                        .WithMany()
                        .HasForeignKey("TipoDocumento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_tipo_documento");

                    b.Navigation("TipoDocumentoNavigation");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Comprobante", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.TipoDocumento", "ClienteDocumentoTipoNavigation")
                        .WithMany()
                        .HasForeignKey("ClienteDocumentoTipo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_comprobante_cliente_tipo");

                    b.HasOne("HotelGenericoApi.Models.EstadoSunat", "EstadoSunat")
                        .WithMany()
                        .HasForeignKey("IdEstadoSunat")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_estado_sunat");

                    b.HasOne("HotelGenericoApi.Models.Estancia", "Estancia")
                        .WithMany()
                        .HasForeignKey("IdEstancia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_comprobante_estancia");

                    b.HasOne("HotelGenericoApi.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_comprobante_venta");

                    b.HasOne("HotelGenericoApi.Models.MetodoPago", "MetodoPagoNavigation")
                        .WithMany()
                        .HasForeignKey("MetodoPago")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_comprobante_metodo_pago");

                    b.HasOne("HotelGenericoApi.Models.TipoComprobante", "TipoComprobanteNavigation")
                        .WithMany()
                        .HasForeignKey("TipoComprobante")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_tipo");

                    b.Navigation("ClienteDocumentoTipoNavigation");

                    b.Navigation("EstadoSunat");

                    b.Navigation("Estancia");

                    b.Navigation("MetodoPagoNavigation");

                    b.Navigation("TipoComprobanteNavigation");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Estancia", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Cliente", "ClienteTitular")
                        .WithMany()
                        .HasForeignKey("IdClienteTitular")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_estancia_cliente");

                    b.HasOne("HotelGenericoApi.Models.Habitacion", "Habitacion")
                        .WithMany("Estancias")
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_estancia_habitacion");

                    b.HasOne("HotelGenericoApi.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_estancia_reserva");

                    b.Navigation("ClienteTitular");

                    b.Navigation("Habitacion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Habitacion", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.EstadoHabitacion", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_habitacion_estado");

                    b.HasOne("HotelGenericoApi.Models.TipoHabitacion", "Tipo")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_habitacion_tipo");

                    b.HasOne("HotelGenericoApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioCambio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_habitacion_usuario");

                    b.Navigation("Estado");

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.HistorialEstadoHabitacion", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_historial_habitacion");

                    b.HasOne("HotelGenericoApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_historial_usuario");

                    b.Navigation("Habitacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Huesped", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_huesped_cliente");

                    b.HasOne("HotelGenericoApi.Models.Estancia", "Estancia")
                        .WithMany("Huespedes")
                        .HasForeignKey("IdEstancia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_huesped_estancia");

                    b.Navigation("Cliente");

                    b.Navigation("Estancia");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.ItemEstancia", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Estancia", "Estancia")
                        .WithMany("ItemsEstancia")
                        .HasForeignKey("IdEstancia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_item_estancia_estancia");

                    b.HasOne("HotelGenericoApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_item_estancia_producto");

                    b.Navigation("Estancia");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.ItemVenta", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_item_venta_producto");

                    b.HasOne("HotelGenericoApi.Models.Venta", "Venta")
                        .WithMany("ItemsVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_item_venta_venta");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Producto", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.AfectacionIgv", "AfectacionIgv")
                        .WithMany()
                        .HasForeignKey("IdAfectacionIgv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_producto_afectacion");

                    b.HasOne("HotelGenericoApi.Models.CategoriaProducto", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_producto_categoria");

                    b.Navigation("AfectacionIgv");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Reserva", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_cliente");

                    b.HasOne("HotelGenericoApi.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_habitacion");

                    b.HasOne("HotelGenericoApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_usuario");

                    b.Navigation("Cliente");

                    b.Navigation("Habitacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Tarifa", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("IdTemporada")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_tarifa_temporada");

                    b.HasOne("HotelGenericoApi.Models.TipoHabitacion", "TipoHabitacion")
                        .WithMany()
                        .HasForeignKey("IdTipoHabitacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tarifa_tipo_habitacion");

                    b.Navigation("Temporada");

                    b.Navigation("TipoHabitacion");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.TransicionEstado", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.EstadoHabitacion", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("IdEstadoActual")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_transicion_actual");

                    b.HasOne("HotelGenericoApi.Models.EstadoHabitacion", "EstadoSiguiente")
                        .WithMany()
                        .HasForeignKey("IdEstadoSiguiente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_transicion_siguiente");

                    b.Navigation("EstadoActual");

                    b.Navigation("EstadoSiguiente");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Usuario", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.RolUsuario", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Venta", b =>
                {
                    b.HasOne("HotelGenericoApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_venta_cliente");

                    b.HasOne("HotelGenericoApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_venta_usuario");

                    b.HasOne("HotelGenericoApi.Models.MetodoPago", "MetodoPagoNavigation")
                        .WithMany()
                        .HasForeignKey("MetodoPago")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_venta_metodo_pago");

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPagoNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Estancia", b =>
                {
                    b.Navigation("Huespedes");

                    b.Navigation("ItemsEstancia");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Habitacion", b =>
                {
                    b.Navigation("Estancias");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelGenericoApi.Models.Venta", b =>
                {
                    b.Navigation("ItemsVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
